### ISSUE TITLE
Get forecast for lat/lng?

### ISSUE THREAD

**Issue by jverzani** [vnegi10/WeatherReport.jl#15]
Hi, nice package. I have some ski areas that don't show up as cities. Is there a way to access the reports by lat/lng? It seems like an easy fix if it isn't already there, as you already map cities to lat/lng coordinates. If you want a PR, let me know.

**Comment by vnegi10** [comment]
Hi John, thanks for reaching out. I have added support to get reports directly via lat/long for all the `plot_hourly_*` functions. It will be available in v0.5.0 via https://github.com/vnegi10/WeatherReport.jl/pull/16.

That leaves `show_current` and `show_daily`. These also need timezone as an input to the API call. I need to think of a way to derive it from the coordinates, which will be better than asking the user for an additional input.

If you see room for other improvements, please don't hesitate to open an issue or a PR.

**Comment by jverzani** [comment]
Thanks. One other thing that I thought would be useful is to allow a user to query their current location, something like the following (which is opt-in):

```
function where_am_I()
    url = "http://ip-api.com/json"
    d = get_api_response(url)
    (lat=d["lat"], lon=d["lon"], tz=d["timezone"])
end
```

**Comment by vnegi10** [comment]
> Thanks. One other thing that I thought would be useful is to allow a user to query their current location, something like the following (which is opt-in):

`where_am_i()` has been added in v0.5.2.

**Comment by jverzani** [comment]
Awesome! Thanks so much.
